services:
<<<<<<< HEAD
  # Frontend Service (React + Vite)
=======
  # Frontend Service (React + Vite) - Web Service
>>>>>>> 9c08fd5259346743904bb84b44be30c533f9b7d8
  - type: web
    name: webthanhtoan-frontend
    env: node
    plan: free
<<<<<<< HEAD
    buildCommand: npm install && npm run build
    startCommand: npm run preview
=======
    buildCommand: cd WebThanhToan && npm install && npm run build
    startCommand: cd WebThanhToan && npm run preview -- --host 0.0.0.0 --port $PORT
>>>>>>> 9c08fd5259346743904bb84b44be30c533f9b7d8
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
<<<<<<< HEAD
        fromService:
          type: web
          name: webthanhtoan-backend
          property: host
    staticPublishPath: ./dist
=======
        value: https://webthanhtoan-backend.onrender.com
>>>>>>> 9c08fd5259346743904bb84b44be30c533f9b7d8

  # Backend Service (Spring Boot)
  - type: web
    name: webthanhtoan-backend
    env: java
    plan: free
<<<<<<< HEAD
    buildCommand: cd backend && ./mvnw clean package -DskipTests
    startCommand: cd backend && java -Xms128m -Xmx512m -XX:+UseG1GC -jar target/*.jar
=======
    buildCommand: cd WebThanhToan/backend && ./mvnw clean package -DskipTests
    startCommand: cd WebThanhToan/backend && java -Xms128m -Xmx512m -XX:+UseG1GC -jar target/*.jar
>>>>>>> 9c08fd5259346743904bb84b44be30c533f9b7d8
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: 10000
      - key: SPRING_DATASOURCE_URL
<<<<<<< HEAD
        fromDatabase:
          name: webthanhtoan-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: webthanhtoan-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: webthanhtoan-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        fromService:
          type: web
          name: webthanhtoan-frontend
          property: host

  # Database Service (PostgreSQL - since Render doesn't support SQL Server)
  - type: pgsql
    name: webthanhtoan-db
    plan: free
    databaseName: webthanhtoan
    user: webthanhtoan_user 
=======
        value: postgresql://webthanhtoan_user:kY7iBclL2xZ8tXvMgwqdCnEusBtl3r8u@dpg-d0v7dt63jp1c73ds1q6g-a/webthanhtoan
      - key: SPRING_DATASOURCE_USERNAME
        value: webthanhtoan_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: kY7iBclL2xZ8tXvMgwqdCnEusBtl3r8u
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: https://webthanhtoan-frontend.onrender.com 
>>>>>>> 9c08fd5259346743904bb84b44be30c533f9b7d8
