services:
  # Frontend Service (React + Vite)
  - type: web
    name: webthanhtoan-frontend
    env: node
    plan: free
    buildCommand: cd WebThanhToan && npm install && npm run build
    startCommand: cd WebThanhToan && npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        fromService:
          type: web
          name: webthanhtoan-backend
          property: host
    staticPublishPath: ./WebThanhToan/dist
  # Backend Service (Spring Boot)
  - type: web
    name: webthanhtoan-backend
    env: java
    plan: free
    buildCommand: cd WebThanhToan/backend && ./mvnw clean package -DskipTests
    startCommand: cd WebThanhToan/backend && java -Xms128m -Xmx512m -XX:+UseG1GC -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: 10000
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: webthanhtoan-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: webthanhtoan-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: webthanhtoan-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        fromService:
          type: web
          name: webthanhtoan-frontend
          property: host
  # Database Service (PostgreSQL)
  - type: database
    name: webthanhtoan-db
    databaseType: postgresql
    plan: free
    databaseName: webthanhtoan
    user: webthanhtoan_user
