services:
  # Dịch vụ Frontend (React + Vite)
  - type: web
    name: webthanhtoan-frontend
    env: node
    plan: free
    buildCommand: cd WebThanhToan && npm install && npm run build
    startCommand: cd WebThanhToan && npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        fromService:
          type: web
          name: webthanhtoan-backend
          property: host
    staticPublishPath: ./WebThanhToan/dist
  # Dịch vụ Backend (Spring Boot)
  - type: web
    name: webthanhtoan-backend
    env: java
    plan: free
    buildCommand: cd WebThanhToan/backend && ./mvnw clean package -DskipTests
    startCommand: cd WebThanhToan/backend && java -Xms128m -Xmx512m -XX:+UseG1GC -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: 10000
      - key: SPRING_DATASOURCE_URL
        value: REPLACE_WITH_RENDER_POSTGRESQL_CONNECTION_STRING
      - key: SPRING_DATASOURCE_USERNAME
        value: REPLACE_WITH_RENDER_POSTGRESQL_USERNAME
      - key: SPRING_DATASOURCE_PASSWORD
        value: REPLACE_WITH_RENDER_POSTGRESQL_PASSWORD
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        fromService:
          type: web
          name: webthanhtoan-frontend
          property: host
