server:
  port: 8080

spring:
  application:
    name: webthanhtoan-backend
  
  datasource:
    url: jdbc:postgresql://postgres:5432/webthanhtoan
    username: webthanhtoan_user
    password: admin123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: false  # Disable flyway for development
  
  security:
    user:
      name: admin
      password: admin123

# JWT Configuration
jwt:
  secret: mySecretKeyForWebThanhToanApplication123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds

# CORS Configuration
cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Logging
logging:
  level:
    com.webthanhtoan: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG 