spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://database:1433;databaseName=WebThanhToan;encrypt=false;trustServerCertificate=true}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: false
        
  # Redis configuration (optional)
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms
      
  # Actuator for health checks
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,prometheus
    endpoint:
      health:
        show-details: always
        
jwt:
  secret: ${JWT_SECRET:mySecretKeyForProductionShouldBeLongerAndMoreSecure}
  expiration: ${JWT_EXPIRATION:86400000}
  
# Logging configuration
logging:
  level:
    com.webthanhtoan: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/webthanhtoan/application.log
    
# Server configuration
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024 