spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/pos_db
    username: pos_user
    password: pos_password
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
  # Actuator for health checks
  management:
    endpoints:
      web:
        exposure:
          include: health,info
    endpoint:
      health:
        show-details: always
        
jwt:
  secret: mySecretKeyForDockerDevelopment123456789012345678901234567890
  expiration: 86400000
  
# CORS Configuration for Docker
cors:
  allowed-origins: http://localhost:3000,http://frontend:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  
# Logging configuration
logging:
  level:
    com.webthanhtoan: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    
# Server configuration
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024 