server:
  port: 8080

spring:
  application:
    name: webthanhtoan-backend
  
  datasource:
    url: jdbc:sqlserver://localhost:1433;instanceName=CBAOSQL;databaseName=WebThanhToan;encrypt=false;trustServerCertificate=true
    username: sa
    password: 12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
  
  # flyway:
  #   enabled: true
  #   baseline-on-migrate: true
  #   baseline-version: 0
  #   locations: classpath:db/migration
  
  security:
    user:
      name: admin
      password: admin123

# JWT Configuration
jwt:
  secret: mySecretKeyForWebThanhToanApplication123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds

# CORS Configuration
cors:
  allowed-origins: http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Logging
logging:
  level:
    com.webthanhtoan: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG 